#!/usr/bin/env python3
#this file create a freq dict of text

import re

def split_to_words(text):
'''split text to words separated by space'''
    text.lower()
    re.sub('/d', '', text)
    words = re.split('/W*', text)
        
class FreqDict:
'''create freq dict'''
    def __init__(self, words):
        self.words = words
        self.create_dict()
    def create_dict(self):
        self.fd = []
        def is_not_in_dict(self, word):
            for i in rang(len(words)):
                if word == words[i]:
                    return i
                else:
                    return True
        for word in words:
            if is_not_in_dict(word) == True:
                self.fd.append(word)
            else: 
                words[is_not_in_dict(word)][1] +=1            

def sort_freq_dict(freq_dict):
'''sort freq dict'''
    sorted(freq_dict, key= lambda dict: dict[1])
