#!/usr/bin/env python3
#test of program freq_dict.py

import freq_dict

fd1 = [['иван', 1], ['анна', 1]] 
fd2 = [['анна', 1], ['иван', 2]] 
sort_freq_dict = [['иван', 2], ['анна', 1]] 


class TestFreqDict(unittest.TestCase):
    def setUp(self):

    def test_split_words(self):
        text = ['Иван Анна', 'Иван - Анна', 'Иван,- Анна', 'Иван Анна дом ']
        list_of_words = [['иван','анна'], ['иван','анна'], ['иван','анна'], ['иван','анна','дом']]
        for (t,l) in zip(text, list_of_words):
            self.assertTrue(freq_dict.split_to_words(t) == l, 'split to words test: wrong split')

    def test_create_freq_dict(self):
        list_of_words1 = ['иван','анна']
        list_of_words2 = ['анна','иван','иван']
        self.assertTrue(list_of_words1.freq_dict.create_dict() == fd1, 'create freq dict test: wrong')
        self.assertTrue(list_of_words2.freq_dict.create_dict() == fd2, 'create freq dict test:wrong split of two words ')

    def test_sort(self):
        self.assertTrue(freq_dict.sort_freq_dict(fd2) == sort_freq_dict, 'sort test: wrong sort')

if __name__ == '__main__':
    unittest.main()
